database:
  mysql:
    addr: 127.0.0.1
    port: 3306
    username: root
    password: 1234
    db: testDB
    connMaxLifetime: 1h
    maxIdleConns: 10
    connMaxIdleTime: 1h
    maxOpenConns: 5
  redis:
    addr: 127.0.0.1
    port: 6379
    username:
    password:
    db: 0
server:
  host: localhost
  port: 8080
  mode: debug